### PR TITLE
Group implement

### LINKED ISSUE #5: Implement GroupOrder API Endpoint logic
As a team we have already created the classes for the GroupOrder endpoint. Implement all the methods related to this class and the logic of the API endpoints.

### LINKED ISSUE #6: Implement Group API Endpoint logic
As a team we have already created the classes for the Group endpoint. Implement all the methods related to this class and the logic of the API endpoints.

### PR DESCRIPTION
**Pull request by capsfly556**
This PR introduces a new REST API controller (GroupsApiController) to manage both groups and their associated orders. The controller provides full CRUD (Create, Read, Update, Delete) functionality for handling group entities and the orders within those groups. This implementation aims to streamline the management of groups and their orders through well-defined API endpoints.

Key updates include:

Get All Groups:

GET /groups/getAllGroups: Retrieves a list of all groups in the system. Returns 404 if no groups exist.
Create a Group:

POST /groups: Allows the creation of a new group with a validated request body. Returns 201 on successful creation.
Update a Group:

PUT /groups/{groupId}: Updates an existing group by its groupId. If the group doesn’t exist, returns 404.
Delete a Group:

DELETE /groups/{groupId}: Deletes a group by its groupId. Handles 404 for non-existing groups and returns 204 on success.
Get All Orders for a Group:

GET /groups/{groupId}/orders: Fetches all orders for a given group.
Create a New Order for a Group:

POST /groups/{groupId}/orders: Adds a new order to the specified group.
Get Specific Order by ID:

GET /groups/{groupId}/orders/{orderId}: Fetches details for a specific order within a group.
Update an Existing Order:

PUT /groups/{groupId}/orders/{orderId}: Updates the details of an order for a given groupId and orderId.
Delete an Order:

DELETE /groups/{groupId}/orders/{orderId}: Deletes an order within a group.

### CODE REVIEW

**Review by marianabuhazi — COMMENTED** [review]
Approved.

**Comment by BeijiaZhang25** [comment]
approved

**Review by Foo2000 — COMMENTED** [review]
Nice implement for the group CRUD

**Review by BeijiaZhang25 — COMMENTED** [review]
It makes sense! Good

**Pull request merged**
