### PR TITLE
Unit test for food provider + javadoc

### LINKED ISSUE #23: Create unit tests for FoodProvider/MenuItem services + controller.

### LINKED ISSUE #29: Add JavaDocs for FoodProvider/MenuItem

### PR DESCRIPTION
**Pull request by BeijiaZhang25**
I created unit tests for food provider service and api, and modify methods in service. 
added javadoc for functions in service and api.

### CODE REVIEW

**Review by Foo2000 — COMMENTED** [review]
Looks good! Good job!

**Review by Foo2000 — APPROVED** [review]

**Review by marianabuhazi — APPROVED** [review]
Thank you for including these tests. Can you add Javadoc though, I don't see it.

**Review by marianabuhazi — CHANGES_REQUESTED** [review]
Please include javadoc

**Review by marianabuhazi — APPROVED** [review]
Thanks for adding javadoc now!

**Review by capsfly556 — APPROVED** [review]
done

**Pull request merged**
