### PR TITLE
Participant modified

### PR DESCRIPTION
**Pull request by marianabuhazi**
This PR provides all the necessary fixes for the PUT and POST issues when dealing with participant orders. Before this, there were a few bugs when we tried to update an existing participant by its ID. I made some changes to the PUT method to check that the participant ID existed. Additionally, I added some parent/child relationships to prevent recursive behavior in the JSON response.

### CODE REVIEW

**Comment by capsfly556** [comment]
approved

**Comment by BeijiaZhang25** [comment]
approved

**Comment by BeijiaZhang25** [comment]
approved

**Review by Foo2000 — COMMENTED** [review]
Good job Marian. This fixed the issues we discussed in the meeting.

**Review by BeijiaZhang25 — COMMENTED** [review]
reviewed for the PUT and POST issues

**Pull request merged**
